<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ru.stqa.pft.test.RestTests" tests="1" skipped="0" failures="1" errors="0" timestamp="2022-12-17T17:06:01" hostname="LAPTOP-6NF5C6OJ" time="97.338">
  <properties/>
  <testcase name="testCreateIssue" classname="ru.stqa.pft.test.RestTests" time="97.338">
    <failure message="java.lang.AssertionError: Sets differ: expected [ru.stqa.pft.test.Issue@13c84bad, ru.stqa.pft.test.Issue@3044e39, ru.stqa.pft.test.Issue@7fccc53b, ru.stqa.pft.test.Issue@32602b40, ru.stqa.pft.test.Issue@63a48b82, ru.stqa.pft.test.Issue@42f06449, ru.stqa.pft.test.Issue@5b0c8431, ru.stqa.pft.test.Issue@68858e3b, ru.stqa.pft.test.Issue@2fbae032, ru.stqa.pft.test.Issue@6e290ba0, ru.stqa.pft.test.Issue@51bb3758, ru.stqa.pft.test.Issue@150b9f02, ru.stqa.pft.test.Issue@6dc856e1, ru.stqa.pft.test.Issue@4b1a24f3, ru.stqa.pft.test.Issue@4393cb3f, ru.stqa.pft.test.Issue@25799f3a, ru.stqa.pft.test.Issue@3f5e1ada, ru.stqa.pft.test.Issue@6249e43d, ru.stqa.pft.test.Issue@25d9900b, ru.stqa.pft.test.Issue@4cb04bc5, ru.stqa.pft.test.Issue@7ff3b7f8] but got [ru.stqa.pft.test.Issue@19a5512e, ru.stqa.pft.test.Issue@602e7b7e, ru.stqa.pft.test.Issue@59a44526, ru.stqa.pft.test.Issue@413cd641, ru.stqa.pft.test.Issue@72a3c369, ru.stqa.pft.test.Issue@61c5b3c8, ru.stqa.pft.test.Issue@1ab357a3, ru.stqa.pft.test.Issue@3d1a046a, ru.stqa.pft.test.Issue@51ce302b, ru.stqa.pft.test.Issue@1d599229, ru.stqa.pft.test.Issue@1dd7c06e, ru.stqa.pft.test.Issue@7003aeea, ru.stqa.pft.test.Issue@506c97a9, ru.stqa.pft.test.Issue@1f59f57, ru.stqa.pft.test.Issue@2282ebb7, ru.stqa.pft.test.Issue@4f1b65f3, ru.stqa.pft.test.Issue@7b7e7266, ru.stqa.pft.test.Issue@565c5579, ru.stqa.pft.test.Issue@63b6d356, ru.stqa.pft.test.Issue@7796162e]" type="java.lang.AssertionError">java.lang.AssertionError: Sets differ: expected [ru.stqa.pft.test.Issue@13c84bad, ru.stqa.pft.test.Issue@3044e39, ru.stqa.pft.test.Issue@7fccc53b, ru.stqa.pft.test.Issue@32602b40, ru.stqa.pft.test.Issue@63a48b82, ru.stqa.pft.test.Issue@42f06449, ru.stqa.pft.test.Issue@5b0c8431, ru.stqa.pft.test.Issue@68858e3b, ru.stqa.pft.test.Issue@2fbae032, ru.stqa.pft.test.Issue@6e290ba0, ru.stqa.pft.test.Issue@51bb3758, ru.stqa.pft.test.Issue@150b9f02, ru.stqa.pft.test.Issue@6dc856e1, ru.stqa.pft.test.Issue@4b1a24f3, ru.stqa.pft.test.Issue@4393cb3f, ru.stqa.pft.test.Issue@25799f3a, ru.stqa.pft.test.Issue@3f5e1ada, ru.stqa.pft.test.Issue@6249e43d, ru.stqa.pft.test.Issue@25d9900b, ru.stqa.pft.test.Issue@4cb04bc5, ru.stqa.pft.test.Issue@7ff3b7f8] but got [ru.stqa.pft.test.Issue@19a5512e, ru.stqa.pft.test.Issue@602e7b7e, ru.stqa.pft.test.Issue@59a44526, ru.stqa.pft.test.Issue@413cd641, ru.stqa.pft.test.Issue@72a3c369, ru.stqa.pft.test.Issue@61c5b3c8, ru.stqa.pft.test.Issue@1ab357a3, ru.stqa.pft.test.Issue@3d1a046a, ru.stqa.pft.test.Issue@51ce302b, ru.stqa.pft.test.Issue@1d599229, ru.stqa.pft.test.Issue@1dd7c06e, ru.stqa.pft.test.Issue@7003aeea, ru.stqa.pft.test.Issue@506c97a9, ru.stqa.pft.test.Issue@1f59f57, ru.stqa.pft.test.Issue@2282ebb7, ru.stqa.pft.test.Issue@4f1b65f3, ru.stqa.pft.test.Issue@7b7e7266, ru.stqa.pft.test.Issue@565c5579, ru.stqa.pft.test.Issue@63b6d356, ru.stqa.pft.test.Issue@7796162e]
	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.assertEquals(Assert.java:1264)
	at org.testng.Assert.assertEquals(Assert.java:1244)
	at ru.stqa.pft.test.RestTests.testCreateIssue(RestTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at org.testng.TestRunner.privateRun(TestRunner.java:724)
	at org.testng.TestRunner.run(TestRunner.java:574)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
	at org.testng.SuiteRunner.run(SuiteRunner.java:302)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
	at org.testng.TestNG.runSuites(TestNG.java:994)
	at org.testng.TestNG.run(TestNG.java:962)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:750)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
